### ISSUE TITLE
Pin content button dont work

### ISSUE THREAD

**Issue by dzovani** [aleph-im/aleph-account#10]
Pin content button dont work
i have enough aleph in wallet, i want to pin CID which is folder , total size 94KB, Pin content button never gets active

![image](https://user-images.githubusercontent.com/6042649/145541156-7d3b40df-86ef-4661-8d42-77939a6b4264.png)

**Comment by BjrInt** [comment]
Old issue but still unresolved. 
This comes from the fact that an IPFS instance is created at page load, regardless if it has already spawned before. I managed to solve the issue on my browser by clearing the IndexedDB. 

The good approach would be to check if an IPFS repo already exists before creating a new one in the [IPFS pin view](https://github.com/aleph-im/aleph-account/blob/d0403a1965118f0653736c00e88897057d5a880c/src/pages/IPFSPin.vue#L361) and in the [NFT storage](https://github.com/aleph-im/aleph-account/blob/19d5c3991de8b7fa28f90b988926781a5c9d77f2/src/pages/NFTStorage.vue#L179) view before creating a new one.
