### ISSUE TITLE
User of aleph account cannot edit the source code of the python example code

### ISSUE THREAD

**Issue by claudioALEPH** [aleph-im/aleph-account#74]
When I try to create a program, the editor doesn't let me edit the sample Python code.

Version: v1.1.0-5-gdd53dd9
Browser: Chrome Version 109.0.5414.87 ARM 64
OS: MacOS 12.6 (21G115)

<img width="898" alt="Screenshot 2023-01-23 at 14 44 35" src="https://user-images.githubusercontent.com/67286727/214055316-e364d26f-82d1-4009-b6dd-0001169a9c23.png">

**Comment by BjrInt** [comment]
I thought I had a similar bug @claudioALEPH , but, on my computer, it is just that the caret is not displayed inside of the code editor unless I write something in it (or erase part of the existing code). 

Can you try to click (once) inside the code editor and try to erase something, and see if it works, like so:
[Screencast from 23-01-23 16:17:35.webm](https://user-images.githubusercontent.com/26065817/214078111-66c429a8-f93d-4e13-81e2-4ace4d1bf3e7.webm)

Even if it is the case, this caret issue still needs to be addressed.

**Comment by claudioALEPH** [comment]
Great catch! It's exactly the same for me.

**Comment by leirbag95** [comment]
I'm on it 👍
